export enum Routes {
  MAIN_NAVIGATOR = 'mainNavigator',
  BURGERS_NAVIGATOR = 'burgersNavigator',
  HOME_NAVIGATOR = 'homeNavigator',
  WALLET_NAVIGATOR = 'walletNavigator',
  START = 'start',
  HOME = 'home',
  BURGERS = 'burgers',
  CUSTOMIZE = 'customize',
  CART = 'cart',
  DELIVERY_DETAILS = 'deliveryDetails',
  ADDRESS = 'address',
  DATE_TIME = 'dateTime',
  WALLET = 'wallet',
}
